### ISSUE TITLE
Netcore 2 Migration

### ISSUE THREAD

**Issue by truccomarcos** [Wolox/netcore-bootstrap#31]
Migrate bootstrap to Netcore 2

https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/
https://docs.microsoft.com/en-us/aspnet/core/aspnetcore-2.0

**Comment by gussiciliano** [comment]
In Preview by now, i think that the better is wait a little
link: https://github.com/dotnet/core/tree/master/release-notes/2.0

**Comment by truccomarcos** [comment]
I dont know how updated that link is. Checkout out this one https://github.com/dotnet/core/blob/master/release-notes/download-archive.md

**Comment by truccomarcos** [comment]
Here are the notes of the released version itself. https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.0.md

**Comment by gussiciliano** [comment]
@truccomarcos Great! I will check right now :D :D
